###obtener todos los tipos de juego
GET http://localhost:3000/api/tipoJuego

### obtener un tipo de juego
GET http://localhost:3000/api/tipoJuego/f1f5a1e4-ee46-479e-a967-52c57b15e7f4

### crear un nuevo tipo de juego
POST http://localhost:3000/api/tipoJuego
Content-Type: application/json

{
  "name": "shooter",
  "description": "Juego de disparos y accion"
}

### modificar un tipo de juego (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/tipoJuego/f1f5a1e4-ee46-479e-a967-52c57b15e7f4
Content-Type: application/json

{
  "name": "RPG",
  "description": "Juego de roles"
}  

### modificar un tipo de juego (PATCH - recurso parcial)
PATCH http://localhost:3000/api/tipoJuego/f1f5a1e4-ee46-479e-a967-52c57b15e7f4
Content-Type: application/json

{
  "description": "Género que se caracteriza por ofrecer al jugador la posibilidad de asumir el papel de uno o varios personajes en un mundo ficticio"
}

### borrar un tipo de juego
DELETE http://localhost:3000/api/tipoJuego/f1f5a1e4-ee46-479e-a967-52c57b15e7f4
